allowBuilds:
  '@tailwindcss/oxide': true
patchedDependencies:
  e-prime@0.10.4: patches/e-prime@0.10.4.patch
  passive-voice@0.1.0: patches/passive-voice@0.1.0.patch
  weasel-words@0.1.1: patches/weasel-words@0.1.1.patch
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  vite-plus: 0.2.5
  vitest: 4.1.10
  '@vitest/browser-playwright': 4.1.10
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
minimumReleaseAgeExclude:
  - '@voidzero-dev/vite-plus-core@0.2.5'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.2.5'
  - '@voidzero-dev/vite-plus-darwin-x64@0.2.5'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.5'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.2.5'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.2.5'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.2.5'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.5'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.2.5'
  - vite-plus@0.2.5
